---
- hosts: localhost
  connection: local 
  become: true


  tasks:
  - name: install packages 
    package:
      name:
        - htop
        - tmux
        - neovim
        - python3-psutil
  - name: copy wallpaper file
    copy:
      src: files/wallpaper.jpg
      dest: /usr/share/backgrounds/ansible-wallpaper.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: rick 
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

  - name: set wallpaper position
    become_user: rick 
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: copy nvim config
    copy:
      src: files/init.lua
      dest: /home/rick/.config/nvim/init.lua
      owner: rick 
      group: rick 
